### PR TITLE
Fix typo in variable name

### PR DESCRIPTION
**Pull request by pierreboissinot**
HTTP header were not sent by the client

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@pierreboissinot Thank you!

**Comment by alexander-schranz** [comment]
@pierreboissinot As you maybe interested in this topic, I will maybe will update the article in some time. We did experiment with it in the current project, and did as example expand that there could be multiple test cases in one markdown file and we extended with fixtures:

Bildschirmfoto 2022-05-05 um 14 01 22

**Comment by pierreboissinot** [comment]
> @pierreboissinot As you maybe interested in this topic, I will maybe will update the article in some time. We did experiment with it in the current project, and did as example expand that there could be multiple test cases in one markdown file and we extended with fixtures:
> 
> Bildschirmfoto 2022-05-05 um 14 01 22

@alexander-schranz Great ! I'm very intereted by this approach of testing. Thank you for the documentation.
I'm using this approach actually in a project and I made some changes to your AbstractApiTestCase:
- extends PHPUnit\Framework\TestCase because I face a PhpBrowserProblem: header are formatted like HTTP_CONTENT_TYPE and I don't want that (maybe I'm wrong). I create a new Symfony\Component\HttpClient\CurlHttpClient
The problem is that for now I hardcoded the base_uri :/


EDIT: for now I'm totally ok to use one .md for one test_case, it keeps small files:
Screenshot_20220505_170010

**Comment by alexander-schranz** [comment]
@pierreboissinot In our case we use the Symfony KernelBrowser client (Symfony WebTestCase). which behave here differently as it works with $_SERVER variable and not with header names. But yeah you would need to adopt that logic to the client you are using. But that I think make it great, you just need to adopt it in your AbstractTestCase once and you could change the client you are using there, you even could go with using a real Curl client or any client you want, but you can change it once for all your tests fast.

**Comment by pierreboissinot** [comment]
> @pierreboissinot In our case we use the Symfony KernelBrowser client (Symfony WebTestCase). which behave here differently as it works with $_SERVER variable and not with header names. But yeah you would need to adopt that logic to the client you are using. But that I think make it great, you just need to adopt it in your AbstractTestCase once and you could change the client you are using there, you even could go with using a real Curl client or any client you want, but you can change it once for all your tests fast.

Your work deserves a small composer library to share this MarkdownBasedAbstractTestCase once the exprience using it is good enough

**Pull request merged**
